### ISSUE TITLE
Gopherjs compilation fails

### ISSUE THREAD

**Issue by nubunto** [nwidger/nintengo#18]
Trying to build Nintengo with `gopherjs build -m` gives me this error:

    ../../../../../go/src/testing/testing.go:614:13: StartTrace not declared by package pprof
    ../../../../../go/src/testing/testing.go:636:3: StopTrace not declared by package pprof

I'm running Go 1.5 from the master branch, version +64e48bb, on a Lubuntu x64 machine.

**Comment by nwidger** [comment]
I just tested and nintengo builds fine with the latest GopherJS and Go 1.4.2.  I haven't actually tried building nintengo (via GopherJS or a normal build) with Go 1.5 at all yet since it hasn't been released.  Not sure if the issue you're seeing is specific to nintengo or a GopherJS/Go 1.5 issue.  I'd be okay waiting to see if this is still an issue after Go 1.5 is officially out.  Thanks for reporting this, though!

**Comment by nubunto** [comment]
Yes, initially I thought it could be an Go 1.5 issue, but hadn't tested compiling with a stable version. Just tried now and it works fine. I wonder what goes wrong with Go 1.5 though.

**Comment by nwidger** [comment]
Not sure, but I definitely plan to check in once Go 1.5 is out and see how things are then.

**Comment by slimsag** [comment]
GopherJS has to be updated with each Go release to handle certain internal stdlib changes, I think. It probably only supports Go 1.4.2 right now.

/cc @neelance

**Comment by neelance** [comment]
Yes, currently only 1.4.2 is supported. I will start an 1.5 branch soon.
